### ISSUE TITLE
Set Up CICD

### ISSUE THREAD

**Issue by AshleyLerma** [J-A-M-M-S/gitLit#13]

**Comment by AshleyLerma** [comment]
- [ ] connect to code climate 
- [ ] connect to circle ci

**Comment by juanlajara** [comment]
How to setup https://circleci.com/. Note: each person has to set it up individually.
![Screen Shot 2020-09-20 at 4 25 38 PM](https://user-images.githubusercontent.com/54958540/93722764-c17e5100-fb5e-11ea-9305-0605b1eca2bf.png)
![Screen Shot 2020-09-20 at 4 26 19 PM](https://user-images.githubusercontent.com/54958540/93722765-c3481480-fb5e-11ea-898d-3b917f966694.png)
